### PR TITLE
HiDPI thumbnail support

### LINKED ISSUE #133: Provide HiDPI thumbnails
Currently, the thumbnails are lowDPI at every scale factor…

Launchpad Details: [#LP1661783](https://bugs.launchpad.net/bugs/1661783) Corentin Noël - 2017-02-04 00:41:12 +0000

### PR DESCRIPTION
**Pull request by davidmhewitt**
Fixes #133 

:tada:

### CODE REVIEW

**Comment by danrabbit** [comment]
I can confirm that this makes thumbnails much sharper on HiDPI :)

**Comment by davidmhewitt** [comment]
This should be *much* better now. Ready for review!

**Comment by danrabbit** [comment]
On first run I got this once and then it never happened again:

```
ERROR:/home/daniel/Projects/photos/src/ThumbnailCache.vala:493:_thumbnail_cache_import_thumbnail: assertion failed: (Dimensions.for_pixbuf (scaled).approx_scaled (size.get_scale ()))
Aborted (core dumped)
```

**Comment by davidmhewitt** [comment]
@danrabbit The only thing I can think that may have caused that is the fact that you tested this before I pushed another commit that fixed a couple of things.

I've just tested from clean, by deleting everything out of `~/.cache/pantheon-photos/thumbs/` and then running this branch and also by running master first, letting it generate some thumbnails in that folder, then running this branch again and experienced no issues. This simulates both the upgrade and clean install processes.

Would you be able to do the same and confirm that it's not one particular image that's causing the issue?

**Comment by danrabbit** [comment]
I cleared the cache and it seems to be working as expected. No crash :)

**Pull request merged**
