### PR TITLE
Add basic SVG support

### LINKED ISSUE #97: Missing SVG viewing/scaling support
Even though vector graphics aren't photos and some editing features aren't applicable SVG support (à la Eye of GNOME, gThumb, Gwenview etc.) would come in handy given that "Photos" is the default image viewer of elementary OS.

Launchpad Details: [#LP1423312](https://bugs.launchpad.net/bugs/1423312) WKraven - 2015-02-18 19:29:30 +0000

### PR DESCRIPTION
**Pull request by donadigo**
Fixes #97.

There are two issues that are present with SVG's, but are not related / caused by this branch:
* crashes with saving to other format than unmodified SVG - this is also currently the case with e.g WebP format

* in the library view, the preview has a black background instead of transparent, this is also a bug in the way Photos assumes to save thumbnails as .jpg, is also present with WebP files

### CODE REVIEW

**Comment by danrabbit** [comment]
I can't confirm that this branch actually adds SVG support. I can't seem to view an SVG file either in the previewer or import one to the library.

Here's the error output I got after trying to import an SVG:

```
** Message: 14:40:00.702: main.vala:350: Shotwell Photo Manager 0.2.4
[INFO 14:40:00.702704] Application.vala:154: Photos version: 0.2.4
[INFO 14:40:00.702736] Application.vala:156: Kernel version: 4.15.0-15-generic
[WARNING 14:40:00.763978] [Gtk] (../../../../gtk/gtkicontheme.c:5497):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.764025] [Gtk] (../../../../gtk/gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.781837] [Gtk] (../../../../gtk/gtkicontheme.c:5497):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.781873] [Gtk] (../../../../gtk/gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.785012] [Gtk] (../../../../gtk/gtkicontheme.c:5497):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.785052] [Gtk] (../../../../gtk/gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.786699] [Gtk] (../../../../gtk/gtkicontheme.c:5497):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.786754] [Gtk] (../../../../gtk/gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.788141] [Gtk] (../../../../gtk/gtkicontheme.c:5497):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.788176] [Gtk] (../../../../gtk/gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.789357] [Gtk] (../../../../gtk/gtkicontheme.c:5497):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.789383] [Gtk] (../../../../gtk/gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.790972] [Gtk] (../../../../gtk/gtkicontheme.c:5497):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.791000] [Gtk] (../../../../gtk/gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.791683] [Gtk] (../../../../gtk/gtkicontheme.c:5497):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:00.791708] [Gtk] (../../../../gtk/gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[FATAL 14:40:00.813527] [GLib-GIO] g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
[FATAL 14:40:00.813562] [GLib] g_variant_get_type: assertion 'value != NULL' failed
[FATAL 14:40:00.813581] [GLib] g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
[FATAL 14:40:00.813603] [GLib] g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed
[FATAL 14:40:00.813624] [GLib] g_variant_unref: assertion 'value != NULL' failed
[FATAL 14:40:00.813646] [GLib-GIO] g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
[FATAL 14:40:00.813661] [GLib] g_variant_get_type: assertion 'value != NULL' failed
[FATAL 14:40:00.813680] [GLib] g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
[FATAL 14:40:00.813700] [GLib] g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed
[FATAL 14:40:00.813714] [GLib] g_variant_unref: assertion 'value != NULL' failed
[FATAL 14:40:00.813732] [GLib-GIO] g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
[FATAL 14:40:00.813768] [GLib] g_variant_get_type: assertion 'value != NULL' failed
[FATAL 14:40:00.813783] [GLib] g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
[FATAL 14:40:00.813804] [GLib] g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed
[FATAL 14:40:00.813827] [GLib] g_variant_unref: assertion 'value != NULL' failed
[FATAL 14:40:00.813897] [GLib-GIO] g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
[FATAL 14:40:00.813918] [GLib] g_variant_get_type: assertion 'value != NULL' failed
[FATAL 14:40:00.813940] [GLib] g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
[FATAL 14:40:00.813961] [GLib] g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed
[FATAL 14:40:00.813983] [GLib] g_variant_unref: assertion 'value != NULL' failed
[FATAL 14:40:00.814005] [GLib-GIO] g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
[FATAL 14:40:00.814027] [GLib] g_variant_get_type: assertion 'value != NULL' failed
[FATAL 14:40:00.814049] [GLib] g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
[FATAL 14:40:00.814088] [GLib] g_variant_get_int32: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT32)' failed
[FATAL 14:40:00.814110] [GLib] g_variant_unref: assertion 'value != NULL' failed
[WARNING 14:40:21.199599] [Gtk] (../../../../gtk/gtkicontheme.c:5497):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:21.199641] [Gtk] (../../../../gtk/gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 14:40:21.208478] BatchImport.vala:1851: Unable to read metadata for /home/daniel/Projects/icons/apps/128/internet-web-browser.svg (unsupported format): continuing to attempt import

(io.elementary.photos:14100): Gtk-WARNING **: 14:40:21.221: drawing failure for widget 'LibraryWindow': cairo_restore() without matching cairo_save()
[WARNING 14:40:21.249632] DirectoryMonitor.vala:929: Skipping hidden file/directory /home/daniel/Pictures/2018/03/15/.goutputstream-3RTLHZ
[FATAL 14:40:27.006895] [GLib-GIO] g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
[FATAL 14:40:27.006945] [GLib] g_variant_get_type: assertion 'value != NULL' failed
[FATAL 14:40:27.006975] [GLib] g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
[FATAL 14:40:27.007004] [GLib] g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed
[FATAL 14:40:27.007032] [GLib] g_variant_unref: assertion 'value != NULL' failed
[FATAL 14:40:27.007065] [GLib-GIO] g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
[FATAL 14:40:27.007094] [GLib] g_variant_get_type: assertion 'value != NULL' failed
[FATAL 14:40:27.007120] [GLib] g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
[FATAL 14:40:27.007145] [GLib] g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed
[FATAL 14:40:27.007173] [GLib] g_variant_unref: assertion 'value != NULL' failed
[FATAL 14:40:27.007203] [GLib-GIO] g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
[FATAL 14:40:27.007231] [GLib] g_variant_get_type: assertion 'value != NULL' failed
[FATAL 14:40:27.007258] [GLib] g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
[FATAL 14:40:27.007285] [GLib] g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed
[FATAL 14:40:27.007311] [GLib] g_variant_unref: assertion 'value != NULL' failed
[FATAL 14:40:27.007393] [GLib-GIO] g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
[FATAL 14:40:27.007422] [GLib] g_variant_get_type: assertion 'value != NULL' failed
[FATAL 14:40:27.007450] [GLib] g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
[FATAL 14:40:27.007474] [GLib] g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed
[FATAL 14:40:27.007499] [GLib] g_variant_unref: assertion 'value != NULL' failed
[FATAL 14:40:27.007526] [GLib-GIO] g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed
[FATAL 14:40:27.007553] [GLib] g_variant_get_type: assertion 'value != NULL' failed
[FATAL 14:40:27.007585] [GLib] g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed
[FATAL 14:40:27.007611] [GLib] g_variant_get_int32: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_INT32)' failed
[FATAL 14:40:27.007636] [GLib] g_variant_unref: assertion 'value != NULL' failed
```

**Comment by jeremypw** [comment]
I confirm that this PR does not add practical ability to view or import svg images with Photos or Photo-Viewer.  The PR description does not say what functionality it is intended to provide or whether it is just a (non-functional) basis for further branches.

Terminal output for attempted viewing an SVG:

jeremy@jeremy-W54-55SU1-SUW:/usr/share/icons/elementary/apps/symbolic$ io.elementary.photos ./accessories-calculator-symbolic.svg 
** Message: 17:29:41.321: main.vala:350: Shotwell Photo Viewer 0.2.4
[INFO 17:29:41.322209] Application.vala:154: Photos version: 0.2.4
[INFO 17:29:41.322253] Application.vala:156: Kernel version: 4.15.0-15-generic
[FATAL 17:29:41.374266] photo_metadata_get_exposure_date_time: assertion 'self != NULL' failed
[WARNING 17:29:41.464455] DirectPhoto.vala:72: Dimensions for image [1] /usr/share/icons/elementary/apps/symbolic/accessories-calculator-symbolic.svg could not be gotten.
[WARNING 17:29:41.464615] Photo.vala:2664: Unable to load metadata: unsupported format
[WARNING 17:29:41.464829] Photo.vala:2664: Unable to load metadata: unsupported format
[FATAL 17:29:41.464860] photo_metadata_get_preview_count: assertion 'self != NULL' failed
[WARNING 17:29:41.464913] EditingHostPage.vala:806: Operation not supported
[WARNING 17:29:41.465734] Photo.vala:2664: Unable to load metadata: unsupported format
[FATAL 17:29:41.465766] photo_metadata_get_preview_count: assertion 'self != NULL' failed
[WARNING 17:29:41.465822] EditingHostPage.vala:907: Operation not supported
[WARNING 17:29:41.466181] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action PrevPhoto
[WARNING 17:29:41.466212] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action NextPhoto
[WARNING 17:29:41.466256] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action FlipHorizontally
[WARNING 17:29:41.466313] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action FlipVertically
[WARNING 17:29:41.466342] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action SetBackground
[FATAL 17:29:41.467850] PixbufCache.vala:275: Unable to readahead [1] /usr/share/icons/elementary/apps/symbolic/accessories-calculator-symbolic.svg: Operation not supported
[WARNING 17:29:41.467931] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action Publish
[WARNING 17:29:41.467984] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action FlipHorizontally
[WARNING 17:29:41.468028] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action FlipVertically
[WARNING 17:29:41.468076] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action Fullscreen
[WARNING 17:29:41.468231] Photo.vala:2664: Unable to load metadata: unsupported format
[FATAL 17:29:41.468259] photo_metadata_get_preview_count: assertion 'self != NULL' failed
[WARNING 17:29:41.468329] EditingHostPage.vala:787: Operation not supported
[FATAL 17:29:41.470320] photo_metadata_get_exposure_date_time: assertion 'self != NULL' failed
[FATAL 17:29:41.471339] photo_metadata_get_exposure_date_time: assertion 'self != NULL' failed
[FATAL 17:29:41.472288] photo_metadata_get_exposure_date_time: assertion 'self != NULL' failed
[FATAL 17:29:41.473157] photo_metadata_get_exposure_date_time: assertion 'self != NULL' failed
[FATAL 17:29:41.473823] photo_metadata_get_exposure_date_time: assertion 'self != NULL' failed
[FATAL 17:29:41.475346] photo_metadata_get_exposure_date_time: assertion 'self != NULL' failed
[FATAL 17:29:41.476341] photo_metadata_get_exposure_date_time: assertion 'self != NULL' failed
[FATAL 17:29:41.477403] photo_metadata_get_exposure_date_time: assertion 'self != NULL' failed
[FATAL 17:29:41.478954] PixbufCache.vala:275: Unable to readahead [1] /usr/share/icons/elementary/apps/symbolic/accessories-calculator-symbolic.svg: Operation not supported
[FATAL 17:29:41.479014] PixbufCache.vala:275: Unable to readahead [9] /usr/share/icons/elementary/apps/symbolic/web-browser-symbolic.svg: Operation not supported
[FATAL 17:29:41.479065] PixbufCache.vala:275: Unable to readahead [3] /usr/share/icons/elementary/apps/symbolic/accessories-text-editor-symbolic.svg: Operation not supported
[FATAL 17:29:41.479110] PixbufCache.vala:275: Unable to readahead [4] /usr/share/icons/elementary/apps/symbolic/internet-mail-symbolic.svg: Operation not supported
[FATAL 17:29:41.479153] PixbufCache.vala:275: Unable to readahead [6] /usr/share/icons/elementary/apps/symbolic/utilities-terminal-symbolic.svg: Operation not supported
[WARNING 17:29:41.479368] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action PrevPhoto
[WARNING 17:29:41.479402] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action NextPhoto
[WARNING 17:29:41.479433] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action FlipHorizontally
[WARNING 17:29:41.479461] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action FlipVertically
[WARNING 17:29:41.479490] Page.vala:263: Page accessories-calculator-symbolic.svg: Unable to locate action SetBackground

(io.elementary.photos:8546): Gtk-WARNING **: 17:29:41.517: drawing failure for widget 'DirectWindow': cairo_restore() without matching cairo_save()

**Comment by cassidyjames** [comment]
@donadigo could you follow up here? What functionality was supposed to be added? Does this still work as you'd expect on Juno?

**Comment by donadigo** [comment]
@cassidyjames this branch meant to make Photos display SVG files correctly, there were no additional features added. I left this branch behind because it had many bugs, but not introduced by itself, but by the base code of Photos. It would require many code fixes to fix crashes / warnings so that this branch could work properly.

**Comment by cassidyjames** [comment]
@donadigo alright, I'll close this for now then.

**Comment by vytenis-nfq** [comment]
I usually opening svg with "Epiphany" browser.

**Pull request closed without merging**
