### PR TITLE
Substitute ActionBar for Toolbar

### LINKED ISSUE #615: More options menu blank
## What Happened

When Photos is resized to be smaller than a certain size, the options/ tools on the bottom bar are moved to a 'more options' drop-down menu that can be viewed by clicking an arrow. However, that menu is blank, despite the options being clickable and functional.

https://user-images.githubusercontent.com/39268094/113976680-0906c900-9874-11eb-93d2-ad3b96820611.mp4

## Expected Behavior

The menu should show text labels for corresponding options/ tools.

## Steps to Reproduce

1. Open a photo in Photos
2. Resize the Photos window to be smaller until the overflow menu arrow appears
3. Click on the overflow menu

## Platform Information

Screenshot from 2021-04-08 13-53-56

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #615 by replacing the future deprecated Gtk.Toolbar with Gtk.ActionBar

As ActionBar has no "insert at position" method some work will be required to maintain (approximately) the same appearance.

 - [x] First compilable version
 - [x] Replace `add` with `pack_start` and `pack_end` everywhere
 - [x] Replace `ToolXXX` widgets with standard widgets everywhere
 - [ ] Maintain appearance as far as possible everywhere (needs Design Team input)

### CODE REVIEW

**Comment by jeremypw** [comment]
All the main functions seem to work as before and the appearance is similar.

**Comment by jeremypw** [comment]
There are large opportunities for improving code style and structure but I have tried to avoid going down that rabbit hole.

**Review by tintou — APPROVED** [review]
Code looks good :)

**Review by danrabbit — APPROVED** [review]
LFG. I need to update the stylesheet for the seps it looks like, but this seems good. Thanks!

**Comment by danrabbit** [comment]
Also fixes #551

**Pull request merged**
