### PR TITLE
Greatly reduces mentioning of "Shotwell"

### LINKED ISSUE #96: we need to change every instance where "Shotwell" appears to "Photos" to maintain consistency.
We don't use the "Shotwell" name anymore, although apareça constantemente. So we need to change that to "Photos" instead. 

e.g. 

"You have already logged in and out of a Google service during this Shotwell session." 

Should be:

"You have already logged in and out of a Google service during this Photos session."

Launchpad Details: [#LP1421628](https://bugs.launchpad.net/bugs/1421628) Davi A. - 2015-02-13 12:30:32 +0000

### PR DESCRIPTION
**Pull request by snowparrot**
Fixes #96 #62 

This PR replace Shotwell with Photos in many places, mostly in comments and strings. 
I didnt refactor and I didnt change ressources.vala, because it may be more important in code and PublishingInterface.vala, because by logic SPIT needs to change into PPIT :P

### CODE REVIEW

**Comment by codygarver** [comment]
Potential reviewers: please don't merge this until I've made a new stable release of Photos, since this is gonna break some translations.

**Comment by tintou** [comment]
I'm in favor of a complete removal of any personification of the application as much as possible
and in some place things can be reformulate like:
`Move the photos to the Photos trash` → `Move photos to the photos trash` (it's not the trash of the application but the trash dedicated to photos items)

**Comment by tintou** [comment]
(talking about user-facing string naturally)

**Comment by danrabbit** [comment]
I'm going to merge this just because it's better than master. But I agree that these strings could probably be a lot better and they don't have to self-reference

**Pull request merged**
