### PR TITLE
Use open directory portal

### PR DESCRIPTION
**Pull request by danirabbit**
We can't read other app's appinfo in the sandbox, so remove the open in submenu. There is a portal for showing a file in Files, so use that portal

### CODE REVIEW

**Comment by zeebok** [comment]
I think my only real reservation is that this creates a tight dependency on Files being on the user's system

**Comment by danirabbit** [comment]
@zeebok Since it uses the portal it launches whatever file browser you have installed :)

**Review by zeebok — APPROVED** [review]
A lot more repeated code than I would've expected

**Comment by danirabbit** [comment]
Yeah this project is wild in that it has so much abstraction and none of it is DRY lol

**Pull request merged**
