### PR TITLE
Fix empty more options

### LINKED ISSUE #615: More options menu blank
## What Happened

When Photos is resized to be smaller than a certain size, the options/ tools on the bottom bar are moved to a 'more options' drop-down menu that can be viewed by clicking an arrow. However, that menu is blank, despite the options being clickable and functional.

https://user-images.githubusercontent.com/39268094/113976680-0906c900-9874-11eb-93d2-ad3b96820611.mp4

## Expected Behavior

The menu should show text labels for corresponding options/ tools.

## Steps to Reproduce

1. Open a photo in Photos
2. Resize the Photos window to be smaller until the overflow menu arrow appears
3. Click on the overflow menu

## Platform Information

Screenshot from 2021-04-08 13-53-56

### PR DESCRIPTION
**Pull request by jeremypw**
Fixes #615 

 - [x] Show sidebar
 - [x] Enhance
 - [x] Adjust
 - [x] Redeye correction
 - [x] Zoom Group (Fit and Original size)
 - [ ] Zoom Group (Slider)

Tools to the left of the Redeye tool are always displayable because of the minimum width of the headerbar so do not need proxy menu items (afaict).

### CODE REVIEW

**Comment by danrabbit** [comment]
Is this just a feature of Gtk.Toolbar or does ActionBar do this too? Gtk.Toolbar is deprecated from Gtk4, so I'm not sure it's worth investing in this direction

**Comment by jeremypw** [comment]
Oh, I didn't realise that :disappointed:   I'll look into how to do it with ActionBar.

**Comment by jeremypw** [comment]
I think ActionBar will not shrink to a size smaller than its contained widgets so the issue will not arise ...

**Comment by jeremypw** [comment]
Withdrawing in favour of a new PR replacing Toolbar with ActionBar

**Pull request closed without merging**
