### PR TITLE
Make StraightenTool Class gobject-style constructed

### PR DESCRIPTION
**Pull request by ZenitsuDev**
For the last one that bases from EditingTool class. (yey!). Also fixed some code style conflicts

### CODE REVIEW

**Comment by ryonakano** [comment]
Actually we have a newline after closing brackets only when there are no another closing bracket: https://docs.elementary.io/develop/writing-apps/code-style#:~:text=Lines%20consisting%20of,1

**Comment by ZenitsuDev** [comment]
Oh okay. I'll fix it.

**Review by ryonakano — APPROVED** [review]
Nice!

**Comment by ZenitsuDev** [comment]
Thanks again @ryonakano!

**Pull request merged**
