### PR TITLE
Make Command Class Gobject-style Constructed

### PR DESCRIPTION
**Pull request by ZenitsuDev**
The Command class which is the parent class of the editing tools can be converted into gobject-style construction, which will also enable editing_tools to be gobject-style constructed.

### CODE REVIEW

**Review by jeremypw — CHANGES_REQUESTED** [review]
Not sure that a construct property should be virtual as it is immutable and the getter should just return it as is (?)  Otherwise it would be better to leave the virtual functions and rename them to something like `get_display_name ()` to show that they do not necessarily return the actual name property.  Could you check the usage of these functions in the rest of the code and decide the appropriate course?

**Comment by jeremypw** [comment]
Also, I think that the property getter will return an unowned string whereas the explicit function will return a string copy.

**Comment by ZenitsuDev** [comment]
okay I will try fixing it

**Comment by jeremypw** [comment]
On closer examination of Photos code it seems that the CommandDescription interface is over-engineering (like a lot of the code).  It is only used in one function!  So I have removed it and replaced it with direct access to Command properties.

**Comment by ZenitsuDev** [comment]
okay. Then

**Comment by ZenitsuDev** [comment]
oh. It is something I was not able to think of right away. Thanks anyway for the new knowledge

**Comment by jeremypw** [comment]
I have pushed a commit to this branch removing that interface.

For future reference, it is better to create a new branch on your fork and change that rather than changing the master branch.

**Comment by ZenitsuDev** [comment]
Okay. Thank You!

**Review by ZenitsuDev — COMMENTED** [review]
I think it is good! Thanks for the help

**Review by jeremypw — APPROVED** [review]

**Pull request merged**
