### PR TITLE
Add Copy Image context menu option (and keyboard shortcut)

### LINKED ISSUE #53: Copy to clipboard feature
Pantheon Photos is already an amazing piece of software. Congratulations and thanks for your efforts!

However, what I very much miss is a copy to clipboard feature. 

Quite often I want to use a photo and upload it to imgur or attach it to an email. Currently I always have to show the photo in the file manager to be able to get it.

Is it possible to implement a copy+c feature by which I can copy the selected photo to the clipboard and can quickly use it in another program?

Thanks for listening!

Launchpad Details: [#LP1309146](https://bugs.launchpad.net/bugs/1309146) Alba Nader - 2014-04-17 19:10:29 +0000

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/61472729-copy-to-clipboard-feature?utm_campaign=plugin&utm_content=tracker%2F60550306&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F60550306&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by TheGag96**
Fixes #53 

Hi! I always thought a feature missing from this image viewer was to be able to copy the viewed image to the clipboard, so I went and made it. 

* Right clicking in a DirectPhotoPage and LibraryPhotoPage will now show "Copy Image" in the context menu, right above "Open In".
* Ctrl+C can be used as a shortcut.

Some gotchas of the design right now:

* You can't do this on the CollectionPage. I wasn't sure how that should work.
* If you've made adjustments to the image, copying will just give you the original image. (I tried many ways to get the the unscaled modified pixbuf but nothing worked; `get_unscaled_pixbuf` still returned a pixbuf scaled to how it appears in the window).

Please let me know if any adjustments need to be made - I've never done anything in Vala, let alone for elementary. Thanks!

### CODE REVIEW

**Comment by jeremypw** [comment]
There is a PR in Files that has a similar intention (I think) but does not use a separate "Copy Image" action.  Rather, the clipboard supplies whatever the recipient requests.  It is a bit simpler although I haven't looked at the use cases here to know whether you could use the same technique.

**Comment by jeremypw** [comment]
You need to de-lint the code in order to pass CI.  You can use the command `io.elementary.vala-lint -d ../` from the build directory to get a list of warnings and errors.  You only need address the errors but it is best not to introduce any new warnings.

Congratulations on your first contribution!  May it be the first of many.

**Comment by jeremypw** [comment]
You can get information about the elementary code style here: https://elementary.io/docs/code/reference#reference.

**Comment by TheGag96** [comment]
Oh, interesting. I didn't even realize there were mechanisms for the program being copied from to handle the pasting logic! Hopefully your PR gets through, looks neat. If it does, then I imagine to keep consistency, would something like that need to be done instead of what I have now (though it'd be more complicated...)?

**Comment by jeremypw** [comment]
It depends on the use cases your PR addresses.  The Files one enhanced an existing "Copy" action with the usual shortcut `<Ctrl>C` so that you can Copy/Paste an image file into e.g a GitHub comment and it would transfer the actual image not the file path as happens in master.   It looks like Photos does nothing if you press `<Ctrl>C` with a photo selected on the library page so in fact it is reasonable to add a new menu option to do that. I think it should be labelled "Copy" not "Copy Image" since it is in the context menu of an image so it is implicit.  I'll have a more detailed look and test soon.

**Comment by jeremypw** [comment]
image

**Comment by jeremypw** [comment]
Sorry must have closed it by mistake.

**Comment by TheGag96** [comment]
Alright, I can take a crack at that. So, from a design perspective, how would you want it to work on the CollectionPage? If you have multiple images selected, does the option show? (I would presume not?)

**Comment by jeremypw** [comment]
@TheGag96 It should be OK to copy multiple items (Files does).  Many if not most likely recipient apps will accept multiple images.  If they don't, nothing bad is likely to happen.  Do you have some intended recipient apps in mind?  Try them out pasting multiple images.

**Comment by TheGag96** [comment]
I don't know of any apps that take multiple image buffers... Would you expect it to copy the files themselves? That would be a different behavior than in the other views.

**Comment by jeremypw** [comment]
You can paste multiple images into GitHub comments and I am pretty sure Inkscape as well, for example.  You can certainly drag and drop multiple images into Inkscape and they become objects.

No, the behaviour in all views should be the same.  If you have problems I can try it out for you.

**Comment by jeremypw** [comment]
Ideally, the app should just "do the right thing" - i.e. a file-manager will get a file, a text editor will get text and an image editor will get an image so you may need to place multiple formats in the clipboard.

**Comment by jeremypw** [comment]
@TheGag96 Sorry, I seem to have lost sight of this PR.  DId you make progress in implementing copying multiple images? Is it something you are still able to work on?

**Comment by TheGag96** [comment]
Holy moly, it's almost been a year. I'm sorry, no, I lost interest... I've since moved on to Linux Mint due to various issues I've had with Elementary.

**Comment by jeremypw** [comment]
OK, sorry again for not following up earlier - I am just going through all the oldest elementary PRs trying to reduce the number outstanding.  I'll fork this PR and maybe try and finish it if I have time.  I'll open a corresponding issue anyway. 

I hope you are enjoying Mint.  Maybe you will give elementary 6 a try when it comes out.

**Comment by TheGag96** [comment]
Again, I apologize for not finishing what I began... If you do take it up, thank you. I just might take a peek when 6 comes out - it was looking pretty slick last time I looked. Here's to hoping the performance/stuttering/vsync issues I was having will be straightened out (though granted, not even Mint is perfect in this regard).

**Comment by jeremypw** [comment]
Please raise issue reports about your display problems in the Gala repo, if you (or someone else) has not already done so.  Hopefully things will be improved in elementary 6.

**Comment by jeremypw** [comment]
Closing in favour of #701, which is based on and extends this PR.

**Pull request closed without merging**
